openapi: 3.0.0
info:
  title: Custom Swagger UI
  version: 1.0.0
paths:
  /users:
    get:
      tags:
        - Users
      summary: Получить список всех пользователей
      description: Возвращает полный список зарегистрированных пользователей из базы данных.
      operationId: get_users
      responses:
        '200':
          description: Успешный ответ со списком пользователей
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserResponse'
components:
  schemas:
    UserResponse:
      type: object
      required:
        - id
        - username
        - email
      properties:
        id:
          type: integer
          description: Уникальный идентификатор пользователя
          example: 1
        username:
          type: string
          description: Имя пользователя
          example: johndoe
        email:
          type: string
          description: Электронная почта пользователя
          example: john@example.com
        full_name:
          type: string
          nullable: true
          description: Полное имя пользователя
          example: John Doe